//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por PROYECTO_ESTRUCTURA_DE_DATOS.rc
//
#define DLG_VENTANAPRINCIPAL            101
#define DLG_INICIOSESION                102
#define DLG_INICIOSESION_REGISTRO       103
#define DLG_REGISTROCARNET              104
#define DLG_REGISTROPERSONAS            105
#define DLG_REGISTROVACUNAS             106
#define IDR_MENU1                       107

#define GB_INICIOSESION_DATOSINICIOSESION         1001
#define TXTB_INICIOSESION_USUARIO       1002
#define TXTB_INICIOSESION_CONTRASENA    1003
#define BTN_INICIOSESION_INGRESAR       1004
#define BTN_INICIOSESION_SALIR          1005
#define BTN_INICIOSESION_REGISTRARSE    1006

#define GB_INICIOSESION_REGISTRO_DATOSREGISTRO         1007
#define TXTB_INICIOSESION_REGISTRO_NOMBRE 1008
#define TXTB_INICIOSESION_REGISTRO_APELLIDOPATERNO 1009
#define TXTB_INICIOSESION_REGISTRO_APELLIDOMATERNO 1010
#define TXTB_INICIOSESION_REGISTRO_USUARIO 1011
#define TXTB_INICIOSESION_REGISTRO_CONTRASENA 1012
#define BTN_INICIOSESION_REGISTRO_REGISTRARSE 1013
#define BTN_INICIOSESION_REGISTRO_SALIR 1014

#define GB_PERSONA_DATOSPERSONA         1015
#define TXTB_PERSONA_NOMBRE             1016
#define TXTB_PERSONA_APELLIDOPATERNO    1017
#define TXTB_PERSONA_APELLIDOMATERNO    1018
#define TXTB_PERSONA_CURP               1019
#define TXTB_PERSONA_RFC                1020
#define TXTB_PERSONA_CALLE              1021
#define TXTB_PERSONA_MUNICIPIO          1022
#define TXTB_PERSONA_TELEFONO           1023
#define TXTB_PERSONA_COLONIA            1024
#define TXTB_PERSONA_ESTADO             1025
#define CB_PERSONA_ESTADOCIVIL          1026
#define CB_PERSONA_SEXO                 1027
#define CB_PERSONA_GRUPOOCUPACIONAL     1028
#define CB_PERSONA_PERFILRIESGO         1029
#define DTP_PERSONA_FECHANACIMIENTO     1030
#define BTN_PERSONA_CARGARDOCUMENTO     1031
#define BTN_PERSONA_CAPTURAR            1032
#define BTN_PERSONA_REGRESAR            1033

#define GB_CARNET_DATOSCARNET           1034
#define TXTB_CARNET_CURP                1035
#define TXTB_CARNET_LOTE                1036
#define TXTB_CARNET_DOSIS               1037
#define CB_CARNET_IDVACUNA                1038
#define CB_CARNET_CENTROVACUNACION      1039
#define CB_CARNET_DOSIS                 1040
#define DTP_CARNET_FECHADOSIS           1041
#define BTN_CARNET_CAPTURAR             1042
#define BTN_CARNET_REGRESAR             1043

#define GB_VACUNA_DATOSVACUNA           1044
#define CB_VACUNA_MARCA                 1045
#define CB_VACUNA_DOSIS                 1046
#define CB_VACUNA_TIPO                  1047
#define TXTB_VACUNA_DESCRIPCION         1048
#define TXTB_VACUNA_CLAVE               1049
#define BTN_VACUNA_CAPTURAR             1050
#define BTN_VACUNA_REGRESAR             1051

#define MENU_REGISTRO_VACUNAS           40017
#define MENU_REGISTRO_PERSONAS          40018
#define MENU_REGISTRO_CARNETS           40019
#define MENU_REPORTE_VACUNAS            40020
#define MENU_REPORTE_PERSONAS           40021
#define MENU_REPORTE_CARNETS            40022
#define MENU_AYUDA_MANUAL               40023
#define MENU_SISTEMA_USUARIOS           40024
#define MENU_SISTEMA_CERRARSESION       40025
#define MENU_SISTEMA_SALIR              40026

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         40028
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
