//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por PROYECTO_ESTRUCTURA_DE_DATOS.rc
//
#define DLG_VENTANAPRINCIPAL            101
#define DLG_INICIOSESION                102
#define IDR_MENU1                       103
#define DLG_REGISTROPERSONAS            108
#define TXTB_INICIOSESION_USUARIO       1001
#define TXTB_INICIOSESION_CONTRASENA    1002
#define BTN_INICIOSESION_INGRESAR       1003
#define BTN_INICIOSESION_SALIR          1004
#define BTN_INICIOSESION_REGISTRARSE    1005
#define TXTB_PERSONA_APELLIDOMATERNO    1007
#define TXTB_PERSONA_NOMBRE             1008
#define TXTB_PERSONA_APELLIDOPATERNO    1009
#define CB_PERSONA_ESTADOCIVIL          1010
#define TXTB_PERSONA_CURP               1011
#define TXTB_PERSONA_RFC                1012
#define TXTB_PERSONA_COLONIA            1015
#define TXTB_PERSONA_CALLE              1016
#define TXTB_PERSONA_MUNICIPIO          1017
#define DTP_PERSONA_FECHANACIMIENTO     1018
#define TXTB_PERSONA_ESTADO             1019
#define GB_PERSONA_DATOSPERSONA         1020
#define TXTB_PERSONA_TELEFONO           1021
#define BTN_PERSONA_CARGARDOCUMENTO     1022
#define CB_PERSONA_SEXO                 1026
#define CB_PERSONA_GRUPOOCUPACIONAL     1027
#define CB_PERSONA_PERFILRIESGO         1028
#define BTN_PERSONA_CAPTURAR            1044
#define BTN_PERSONA_REGRESAR            1045
#define MENU_REGISTRO_VACUNAS           40017
#define MENU_REGISTRO_PERSONAS          40018
#define MENU_REGISTRO_CARNET            40019
#define MENU_REPORTE_VACUNAS            40020
#define MENU_REPORTE_PERSONAS           40021
#define MENU_REPORTE_CARNETS            40022
#define MENU_REGISTRO_CARNETS           40023
#define MENU_AYUDA_MANUAL               40024
#define MENU_SISTEMA_USUARIOS           40025
#define MENU_SISTEMA_CERRARSESION       40026
#define MENU_SISTEMA_SALIR              40027

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40028
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
